name: Haskell Stack CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Haskell Stack
      run: |
        curl -sSL https://get.haskellstack.org/ | sh

    - name: Build and Test
      run: |
        stack setup
        stack build --test