name: test hashcons

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - shell: bash
      run: cabal update
    - shell: bash
      run: cabal build --enable-tests
    - shell: bash
      run: cabal test
