name: Haskell CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Haskell
      uses: actions/setup-haskell@v1
      with:
        ghc-version: '9.4.6' 

    - name: Checkout code
      uses: actions/checkout@v1

    - name: Cache dependencies
      uses: actions/cache@v1
      with:
        path: ~/.stack
        key: ${{ runner.os }}-${{ hashFiles('stack.yaml') }}
        restore-keys: |
          ${{ runner.os }}-
    - name: Test build
      run: |
        stack build --test

