name: Haskell CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Haskell
      uses: actions/setup-haskell@v1
      with:
        ghc-version: '9.4.6'  # or your desired GHC version

    - name: Build
      run: |
        cabal update
        cabal build --enable-tests

    - name: Test
      run: cabal test
