name: test hashcons

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - shell: bash
      run: cabal update
    - shell: bash
      run: ghcup --version
    - shell: bash
      run: ghcup set ghc 9.4.7
    - shell: bash
      run: cabal build --enable-tests
    - shell: bash
      run: cabal test
